apiVersion: v1
kind: Service
metadata:
  name: mongo-job-service
  labels:
    app: mongo-job
spec:
  selector:
    app: mongo-job
  type: NodePort
  ports:
    - nodePort: 32325
      port: 27017
      protocol: TCP
      targetPort: 27017
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-job-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-job-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-job
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-job
    spec:
      containers:
      - image: mongo
        name: mongo-job
        ports:
        - containerPort: 27017
          name: mongo-job
        volumeMounts:
        - name: mongo-job-persistent-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-job-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-job-pv-claim
